# Generated by Django 5.1.7 on 2025-07-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="memo",
            field=models.TextField(blank=True),
        ),
    ]
